INSERT INTO member(address, email, name, nickname, password, phone_number, point, role_type)
VALUES ('test address1', 'test1', '일반유저_ID', '일반유저_ID', '$2a$10$2GQ29M4weMNnaN3uCiSra.kkW1SLsDX5mPnDYAGYFFbHy1j7f0PfK', '010-5651-5957', 15000, 'MEMBER');
INSERT INTO member(address, email, name, nickname, password, phone_number, point, role_type)
VALUES ('test address2', 'test2', '판매자_ID', '판매자_ID', '$2a$10$2GQ29M4weMNnaN3uCiSra.kkW1SLsDX5mPnDYAGYFFbHy1j7f0PfK', '010-8765-1234', 20000, 'SELLER');
INSERT INTO member(address, email, name, nickname, password, phone_number, point, role_type)
VALUES ('test address3', 'test3', '정비사_ID', '정비사_ID', '$2a$10$2GQ29M4weMNnaN3uCiSra.kkW1SLsDX5mPnDYAGYFFbHy1j7f0PfK', '010-8765-1234', 5000, 'MECHANIC');

INSERT INTO seller(company_address, company_name, company_number, company_phone_number, description, member_id)
VALUES ('company_address', 'company_name', 'company_number', 'company_phone_number', 'seller description', 2);
INSERT INTO repair_shop(description, shop_name, shop_phone_number, member_id)
VALUES ('mechanic description', 'shop_name', 'shop_phone_number', 3);

-- INSERT INTO kind(name) VALUES ('그래픽카드');
-- INSERT INTO kind(name) VALUES ('cpu');
-- INSERT INTO kind(name) VALUES ('프린터기');
-- INSERT INTO kind(name) VALUES ('메인보드');
-- INSERT INTO kind(name) VALUES ('RAM');
-- INSERT INTO kind(name) VALUES ('SSD');
-- INSERT INTO kind(name) VALUES ('HDD');
-- INSERT INTO kind(name) VALUES ('케이스');
-- INSERT INTO kind(name) VALUES ('파워');
-- INSERT INTO kind(name) VALUES ('쿨러');
-- INSERT INTO kind(name) VALUES ('키보드');
-- INSERT INTO kind(name) VALUES ('마우스');
-- INSERT INTO kind(name) VALUES ('SSD');
-- INSERT INTO kind(name) VALUES ('HDD');
-- INSERT INTO kind(name) VALUES ('NAS');
-- INSERT INTO kind(name) VALUES ('USB');
-- INSERT INTO kind(name) VALUES ('공유기');
-- INSERT INTO kind(name) VALUES ('USB허브');
-- INSERT INTO kind(name) VALUES ('랜카드');
-- INSERT INTO kind(name) VALUES ('스위치허브');
-- INSERT INTO kind(name) VALUES ('컴퓨터');
-- INSERT INTO kind(name) VALUES ('노트북');
-- INSERT INTO kind(name) VALUES ('휴대폰');
-- INSERT INTO kind(name) VALUES ('태블릿');
--
-- INSERT INTO category(category_name) VALUES ('컴퓨터');
-- INSERT INTO category(category_name) VALUES ('노트북');
-- INSERT INTO category(category_name) VALUES ('휴대폰');
-- INSERT INTO category(category_name) VALUES ('테블릿');
--
-- INSERT INTO brand(brand_name) VALUES ('삼성');
-- INSERT INTO brand(brand_name) VALUES ('LG');
-- INSERT INTO brand(brand_name) VALUES ('기가바이트');
-- INSERT INTO brand(brand_name) VALUES ('지포스');
-- INSERT INTO brand(brand_name) VALUES ('인텔');
-- INSERT INTO brand(brand_name) VALUES ('라이젠');
-- INSERT INTO brand(brand_name) VALUES ('MSI');
-- INSERT INTO brand(brand_name) VALUES ('ASUS');
-- INSERT INTO brand(brand_name) VALUES ('레노버');
-- INSERT INTO brand(brand_name) VALUES ('애플');
-- INSERT INTO brand(brand_name) VALUES ('샤오미');
--
-- # 카테고리-브랜드
-- # 컴퓨터
-- INSERT INTO category_brand(brand_id, category_id) VALUES (1, 1);
-- INSERT INTO category_brand(brand_id, category_id) VALUES (2, 1);
-- INSERT INTO category_brand(brand_id, category_id) VALUES (3, 1);
-- INSERT INTO category_brand(brand_id, category_id) VALUES (4, 1);
-- INSERT INTO category_brand(brand_id, category_id) VALUES (5, 1);
-- INSERT INTO category_brand(brand_id, category_id) VALUES (6, 1);
-- INSERT INTO category_brand(brand_id, category_id) VALUES (7, 1);
--
-- # 노트북
-- INSERT INTO category_brand(brand_id, category_id) VALUES (1, 2);
-- INSERT INTO category_brand(brand_id, category_id) VALUES (2, 2);
-- INSERT INTO category_brand(brand_id, category_id) VALUES (3, 2);
-- INSERT INTO category_brand(brand_id, category_id) VALUES (4, 2);
-- INSERT INTO category_brand(brand_id, category_id) VALUES (5, 2);
-- INSERT INTO category_brand(brand_id, category_id) VALUES (7, 2);
-- INSERT INTO category_brand(brand_id, category_id) VALUES (8, 2);
-- INSERT INTO category_brand(brand_id, category_id) VALUES (9, 2);
-- INSERT INTO category_brand(brand_id, category_id) VALUES (10, 2);
--
-- # 휴대폰
-- INSERT INTO category_brand(brand_id, category_id) VALUES (1, 3);
-- INSERT INTO category_brand(brand_id, category_id) VALUES (10, 3);
-- INSERT INTO category_brand(brand_id, category_id) VALUES (11, 3);
--
-- # 테블릿
-- INSERT INTO category_brand(brand_id, category_id) VALUES (1, 4);
-- INSERT INTO category_brand(brand_id, category_id) VALUES (10, 4);
-- INSERT INTO category_brand(brand_id, category_id) VALUES (11, 4);
--
-- # 구독권
-- set @now = '';
-- SELECT NOW() into @now;
-- INSERT INTO subscription(start_date, member_id) values (@now, 1);
-- INSERT INTO subscription(start_date, member_id) values (@now, 2);
--
-- # 제품
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2022 맥북에어 MLY33KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2021 맥북프로16 MK183KH/A M1 Pro', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2023 맥북프로14 MPHE3KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2023 맥북프로14 MPHH3KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2022 맥북에어 MLXY3KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2022 맥북에어 MLXW3KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2023 맥북프로16 MNW83KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2021 맥북프로14 MKGQ3KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2022 맥북에어 MLY13KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2022 맥북프로13 MNEJ3KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2023 맥북프로16 MNWD3KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2023 맥북프로14 MPHK3KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2021 맥북프로16 MK1H3KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2022 맥북프로13 MNEH3KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2022 맥북에어 MLXX3KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2023 맥북프로16 MNWA3KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2023 맥북프로16 MNWE3KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2022 맥북프로13 MNEP3KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2020 맥북에어 MGN63KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2023 맥북프로14 MPHG3KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2023 맥북프로14 MPHF3KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2022 맥북프로13 MNEQ3KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2022 맥북에어 MLY03KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2021 맥북프로14 MKGP3KH/A M1 Pro 8core', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2023 맥북프로16 MNW93KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2020 맥북에어 MGN93KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2020 맥북프로13 MYD82KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2021 맥북프로14 MKGR3KH/A M1 Pro 8core', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2022 맥북에어 MLY43KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2021 맥북프로16 MK193KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2023 맥북프로16 MNWC3KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2020 맥북프로13 MWP52KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2020 맥북프로13 MYD92KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2020 맥북프로13 MWP82KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2020 맥북프로13 MYDC2KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2021 맥북프로16 MK1A3KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2020 맥북프로13 MWP72KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2021 맥북프로16 MK1E3KH/A M1 Pro', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2023 맥북프로14 MPHJ3KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2020 맥북에어 MGN73KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2020 맥북에어 MGND3KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2022 맥북에어 MLY23KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2021 맥북프로14 MKGP3KH/A M1 Pro 10core', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2021 맥북프로14 MKGT3KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2019 맥북프로16 MVVJ2KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2021 맥북프로16 MK183KH/A M1 Max', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2021 맥북프로16 MK1F3KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2019 맥북프로16 MVVK2KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2020 맥북프로13 MWP42KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2019 맥북프로13 MV962KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2018 맥북프로15 MR942KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2021 맥북프로14 MKGP3KH/A M1 Max', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2021 맥북프로14 MKGR3KH/A M1 Max', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2018 맥북프로15 MR932KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2020 맥북에어 MGNA3KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2017 맥북프로13 MPXT2KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2020 맥북에어 MGN93KH/A CTO', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2019 맥북프로16 MVVM2KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2019 맥북프로16 MVVL2KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2020 맥북에어 MWTL2KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2019 맥북프로13 MUHN2KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2019 맥북에어 MVFJ2KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2018 맥북프로13 MR9V2KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2020 맥북에어 MVH22KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2018 맥북프로13 MR9Q2KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2017 맥북프로15 MPTT2KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2020 맥북에어 MGNE3KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2020 맥북에어 MWTJ2KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2019 맥북프로13 MV972KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2015 맥북프로15 MJLQ2KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2018 맥북프로13 MR9U2KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2017 맥북프로15 MPTR2KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2021 맥북프로14 MKGR3KH/A M1 Pro 10core', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2018 맥북프로13 MR9R2KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2018 맥북프로15 MR962KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2017 맥북프로13 MPXQ2KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2016 맥북프로13 MLH12KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2019 맥북프로15 MV942KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2017 맥북프로13 MPXW2KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2017 맥북프로13 MPXV2KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2016 맥북프로15 MLW72KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2020 맥북에어 MVH52KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2017 맥북프로13 MPXU2KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2020 맥북에어 MVH42KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2019 맥북프로15 MV952KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2019 맥북에어 MVFN2KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2019 맥북프로15 MV902KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2019 맥북프로15 MV912KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2018 맥북프로15 MUQH2KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('맥북에어 MC503KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2015 맥북에어13 MMGF2KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2019 맥북에어 MVFK2KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2019 맥북에어 MVFM2KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2019 맥북프로13 MV9A2KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2021 맥북프로16 MK1E3KH/A M1 Max', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2019 맥북프로13 MUHQ2KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2016 맥북프로13 MNQG2KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('맥북에어 MC965KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2018 맥북프로15 MR952KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2017 맥북프로13 MPXX2KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2016 맥북프로13 MLL42KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2020 맥북에어 MGN63KH/A CTO', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2020 맥북에어 MWTK2KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2015 맥북 MK4N2KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('맥북프로 MD101KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2020 맥북프로13 MYDA2KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2018 맥북에어 MRE92KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2018 맥북에어 MREF2KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2018 맥북에어 MREE2KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('맥북프로 MC700KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2016 맥북 MLHE2KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2014 맥북프로13 ME865KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2017 맥북 MNYH2KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2016 맥북 MMGM2KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2020 맥북에어 MVH22KH/A CTO', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2022 맥북프로13 MNEH3LL/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2019 맥북프로13 MUHP2KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2019 맥북프로13 MUHR2KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2019 맥북에어 MVFL2KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2019 맥북에어 MVFH2KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2019 맥북프로13 MV992KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2019 맥북프로15 MV922KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2019 맥북프로15 MV932KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2018 맥북에어 MREC2KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2018 맥북에어 MREA2KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2018 맥북에어 MRE82KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2018 맥북프로15 MR972KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2017 맥북프로13 MPXR2KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2017 맥북프로13 MPXY2KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2017 맥북프로15 MPTU2KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2017 맥북프로15 MPTV2KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2016 맥북프로13 MLVP2KH/A', true, 22);
-- INSERT INTO product(product_name, role_type, kind_id) VALUES ('2016 맥북프로15 MLH32KH/A', true, 22);
--
--
-- # 포인트 이용내역
-- set @now = '';
-- SELECT NOW() into @now;
-- INSERT INTO point_history(date, point, service_name, service_type, member_id) VALUES (@now, 50000, '아이폰12 구매', '상품 구매', 1);
-- INSERT INTO point_history(date, point, service_name, service_type, member_id) VALUES (@now, 10000, '리뷰 추천 누적 10회', '리뷰 추천 누적', 1);
-- INSERT INTO point_history(date, point, service_name, service_type, member_id) VALUES (@now, 15000, '리뷰 추천 누적 20회', '리뷰 추천 누적', 2);

--커뮤니티 글
INSERT INTO post (content, date, report, title, member_id) VALUES ('Post content 1', '2023-01-01 00:00:00', 0, 'Title 1', 1);
INSERT INTO post (content, date, report, title, member_id) VALUES ('Post content 2', '2023-01-02 00:00:00', 0, 'Title 2', 2);
INSERT INTO post (content, date, report, title, member_id) VALUES ('Post content 3', '2023-01-03 00:00:00', 0, 'Title 3', 3);
INSERT INTO post (content, date, report, title, member_id) VALUES ('Post content 4', '2023-01-04 00:00:00', 0, 'Title 4', 1);
INSERT INTO post (content, date, report, title, member_id) VALUES ('Post content 5', '2023-01-05 00:00:00', 0, 'Title 5', 2);
INSERT INTO post (content, date, report, title, member_id) VALUES ('Post content 6', '2023-01-06 00:00:00', 0, 'Title 6', 3);
INSERT INTO post (content, date, report, title, member_id) VALUES ('Post content 7', '2023-01-07 00:00:00', 0, 'Title 7', 1);
INSERT INTO post (content, date, report, title, member_id) VALUES ('Post content 8', '2023-01-08 00:00:00', 0, 'Title 8', 2);
INSERT INTO post (content, date, report, title, member_id) VALUES ('Post content 9', '2023-01-09 00:00:00', 0, 'Title 9', 3);
INSERT INTO post (content, date, report, title, member_id) VALUES ('Post content 10', '2023-01-10 00:00:00', 0, 'Title 10', 1);
INSERT INTO post (content, date, report, title, member_id) VALUES ('Post content 11', '2023-01-11 00:00:00', 0, 'Title 11', 2);
INSERT INTO post (content, date, report, title, member_id) VALUES ('Post content 12', '2023-01-12 00:00:00', 0, 'Title 12', 3);
INSERT INTO post (content, date, report, title, member_id) VALUES ('Post content 13', '2023-01-13 00:00:00', 0, 'Title 13', 1);
INSERT INTO post (content, date, report, title, member_id) VALUES ('Post content 14', '2023-01-14 00:00:00', 0, 'Title 14', 2);
INSERT INTO post (content, date, report, title, member_id) VALUES ('Post content 15', '2023-01-15 00:00:00', 0, 'Title 15', 3);
INSERT INTO post (content, date, report, title, member_id) VALUES ('Post content 16', '2023-01-01 00:00:00', 0, 'Title 16', 1);
INSERT INTO post (content, date, report, title, member_id) VALUES ('Post content 17', '2023-01-01 00:00:00', 0, 'Title 17', 2);
INSERT INTO post (content, date, report, title, member_id) VALUES ('Post content 18', '2023-01-01 00:00:00', 0, 'Title 18', 3);
INSERT INTO post (content, date, report, title, member_id) VALUES ('Post content 19', '2023-01-01 00:00:00', 0, 'Title 19', 1);
INSERT INTO post (content, date, report, title, member_id) VALUES ('Post content 20', '2023-01-01 00:00:00', 0, 'Title 20', 2);
INSERT INTO post (content, date, report, title, member_id) VALUES ('Post content 21', '2023-01-01 00:00:00', 0, 'Title 21', 3);
INSERT INTO post (content, date, report, title, member_id) VALUES ('Post content 22', '2023-01-01 00:00:00', 0, 'Title 22', 1);
INSERT INTO post (content, date, report, title, member_id) VALUES ('Post content 23', '2023-01-01 00:00:00', 0, 'Title 23', 2);
INSERT INTO post (content, date, report, title, member_id) VALUES ('Post content 24', '2023-01-01 00:00:00', 0, 'Title 24', 3);
INSERT INTO post (content, date, report, title, member_id) VALUES ('Post content 25', '2023-01-01 00:00:00', 0, 'Title 25', 1);
INSERT INTO post (content, date, report, title, member_id) VALUES ('Post content 26', '2023-01-01 00:00:00', 0, 'Title 26', 2);
INSERT INTO post (content, date, report, title, member_id) VALUES ('Post content 27', '2023-01-01 00:00:00', 0, 'Title 27', 3);
INSERT INTO post (content, date, report, title, member_id) VALUES ('Post content 28', '2023-01-01 00:00:00', 0, 'Title 28', 1);
INSERT INTO post (content, date, report, title, member_id) VALUES ('Post content 29', '2023-01-01 00:00:00', 0, 'Title 29', 2);
INSERT INTO post (content, date, report, title, member_id) VALUES ('Post content 30', '2023-01-01 00:00:00', 0, 'Title 30', 3);
INSERT INTO post (content, date, report, title, member_id) VALUES ('Post content 31', '2023-01-01 00:00:00', 0, 'Title 31', 1);
INSERT INTO post (content, date, report, title, member_id) VALUES ('Post content 32', '2023-01-01 00:00:00', 0, 'Title 32', 2);
INSERT INTO post (content, date, report, title, member_id) VALUES ('Post content 33', '2023-01-01 00:00:00', 0, 'Title 33', 3);
INSERT INTO post (content, date, report, title, member_id) VALUES ('Post content 34', '2023-01-01 00:00:00', 0, 'Title 34', 1);
INSERT INTO post (content, date, report, title, member_id) VALUES ('Post content 35', '2023-01-01 00:00:00', 0, 'Title 35', 2);
INSERT INTO post (content, date, report, title, member_id) VALUES ('Post content 36', '2023-01-01 00:00:00', 0, 'Title 36', 3);
INSERT INTO post (content, date, report, title, member_id) VALUES ('Post content 37', '2023-01-01 00:00:00', 0, 'Title 37', 1);
INSERT INTO post (content, date, report, title, member_id) VALUES ('Post content 38', '2023-01-01 00:00:00', 0, 'Title 38', 2);
INSERT INTO post (content, date, report, title, member_id) VALUES ('Post content 39', '2023-01-01 00:00:00', 0, 'Title 39', 3);
INSERT INTO post (content, date, report, title, member_id) VALUES ('Post content 40', '2023-01-01 00:00:00', 0, 'Title 40', 1);
INSERT INTO post (content, date, report, title, member_id) VALUES ('Post content 41', '2023-01-01 00:00:00', 0, 'Title 41', 2);
INSERT INTO post (content, date, report, title, member_id) VALUES ('Post content 42', '2023-01-01 00:00:00', 0, 'Title 42', 3);
INSERT INTO post (content, date, report, title, member_id) VALUES ('Post content 43', '2023-01-01 00:00:00', 0, 'Title 43', 1);
INSERT INTO post (content, date, report, title, member_id) VALUES ('Post content 44', '2023-01-01 00:00:00', 0, 'Title 44', 2);
INSERT INTO post (content, date, report, title, member_id) VALUES ('Post content 45', '2023-01-01 00:00:00', 0, 'Title 45', 3);
INSERT INTO post (content, date, report, title, member_id) VALUES ('Post content 46', '2023-01-01 00:00:00', 0, 'Title 46', 1);
INSERT INTO post (content, date, report, title, member_id) VALUES ('Post content 47', '2023-01-01 00:00:00', 0, 'Title 47', 2);
INSERT INTO post (content, date, report, title, member_id) VALUES ('Post content 48', '2023-01-01 00:00:00', 0, 'Title 48', 3);
INSERT INTO post (content, date, report, title, member_id) VALUES ('Post content 49', '2023-01-01 00:00:00', 0, 'Title 49', 1);
INSERT INTO post (content, date, report, title, member_id) VALUES ('Post content 50', '2023-01-01 00:00:00', 0, 'Title 50', 2);
INSERT INTO post (content, date, report, title, member_id) VALUES ('Post content 51', '2023-01-01 00:00:00', 0, 'Title 51', 3);
INSERT INTO post (content, date, report, title, member_id) VALUES ('Post content 52', '2023-01-01 00:00:00', 0, 'Title 52', 1);
INSERT INTO post (content, date, report, title, member_id) VALUES ('Post content 53', '2023-01-01 00:00:00', 0, 'Title 53', 2);
INSERT INTO post (content, date, report, title, member_id) VALUES ('Post content 54', '2023-01-01 00:00:00', 0, 'Title 54', 3);
INSERT INTO post (content, date, report, title, member_id) VALUES ('Post content 55', '2023-01-01 00:00:00', 0, 'Title 55', 1);
INSERT INTO post (content, date, report, title, member_id) VALUES ('Post content 56', '2023-01-01 00:00:00', 0, 'Title 56', 2);
INSERT INTO post (content, date, report, title, member_id) VALUES ('Post content 57', '2023-01-01 00:00:00', 0, 'Title 57', 3);
INSERT INTO post (content, date, report, title, member_id) VALUES ('Post content 58', '2023-01-01 00:00:00', 0, 'Title 58', 1);
INSERT INTO post (content, date, report, title, member_id) VALUES ('Post content 59', '2023-01-01 00:00:00', 0, 'Title 59', 2);
INSERT INTO post (content, date, report, title, member_id) VALUES ('Post content 60', '2023-01-01 00:00:00', 0, 'Title 60', 3);
INSERT INTO post (content, date, report, title, member_id) VALUES ('Post content 61', '2023-01-01 00:00:00', 0, 'Title 61', 1);